---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wireguard-kubernetes
rules:
- apiGroups: [""] # core API group
  resources: ["nodes"]
  verbs: ["patch", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wireguard-kubernetes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wireguard-kubernetes
subjects:
- kind: ServiceAccount
  name: default
  namespace: wireguard-kubernetes
